---
version: 2
jobs:
  pr_check:
    working_directory: ~/webapp
    docker:
      - image: circleci/node:10.15.3
      - image: circleci/mongo:4.2.5
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependency and compile code
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run unit test
          command: npm test
workflows:
  version: 2
  pr-check:
    jobs:
      - pr_check
